<a href="https://colab.research.google.com/github/shivamsen23/Machine-learning/blob/main/csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## ***1.IMPORTING PANDAS***

In [ ]:
import pandas as pd

## **2.Opening a local CSV file**

In [ ]:
df=pd.read_csv('/content/airlines_flights_data.csv')
df

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

**3.Opening a CSV file from url**

In [ ]:
import requests

import pandas as pd
from io import StringIO


url = ""

headers = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.5",
    "Accept-Encoding": "gzip, deflate, br",
    "Connection": "keep-alive"
}

req = requests.get(url, headers=headers)
data = StringIO(req.text)
df = pd.read_csv(data)

print(df.head())

4.Sep Paramater

In [ ]:
df=pd.read_csv('/content/airlines_flights_data.csv',sep='\t',names=['sno','name']) #if we are working with tsv file then seperate
# data with tab sperated values and name is used to name ur column if column name is not present
df

In [ ]:
5

**5.Header Parmater ** - sometimes our first row start with column name row , to move row data from next row start with 1 not 0

In [ ]:
pd.read_csv('test.csv',header=1);

**6.use_cols Paramater**

In [ ]:
pd.read_csv('test.csv',usecols=['id','name','gender']) #use only that col which uh want

**SKIP BAD LINES**

In [ ]:
pd.read_csv('text.csv',sep=';',error_bad_lines=False) #it will skip those rows which cause problem

**Handling Dates**

In [ ]:
pd.read_csv('text.csv',parse_dates=['date']).info() # sometimes bydefault date is string to use date filter and method convert this string into date datatype